name: Main CI/CD workflow
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  # Ensure code style is respected by running `rustfmt` over all code
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  # Ensure there are no Clippy warnings
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -Dwarnings
